// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/teleport.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AppStatePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_UiPromiseResultStringPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIPromiseResultString;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_UiResolverUiPairReactionPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIResolverUIPairReaction;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  UiPromiseResultString
  dco_decode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIPromiseResultString(
    dynamic raw,
  );

  @protected
  UiResolverUiPairReaction
  dco_decode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIResolverUIPairReaction(
    dynamic raw,
  );

  @protected
  AppState
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    dynamic raw,
  );

  @protected
  AppState
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    dynamic raw,
  );

  @protected
  AppState
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    dynamic raw,
  );

  @protected
  UiPromiseResultString
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIPromiseResultString(
    dynamic raw,
  );

  @protected
  UiResolverUiPairReaction
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIResolverUIPairReaction(
    dynamic raw,
  );

  @protected
  RustStreamSink<InboundFileEvent> dco_decode_StreamSink_inbound_file_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<InboundPair> dco_decode_StreamSink_inbound_pair_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<OutboundFileStatus>
  dco_decode_StreamSink_outbound_file_status_Sse(dynamic raw);

  @protected
  RustStreamSink<UIConnectionQualityUpdate>
  dco_decode_StreamSink_ui_connection_quality_update_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  InboundPair dco_decode_box_autoadd_inbound_pair(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  InboundFileEvent dco_decode_inbound_file_event(dynamic raw);

  @protected
  InboundFileStatus dco_decode_inbound_file_status(dynamic raw);

  @protected
  InboundPair dco_decode_inbound_pair(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  OutboundFileStatus dco_decode_outbound_file_status(dynamic raw);

  @protected
  PairingResponse dco_decode_pairing_response(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  U8Array6 dco_decode_u_8_array_6(dynamic raw);

  @protected
  UIConnectionQuality dco_decode_ui_connection_quality(dynamic raw);

  @protected
  UIConnectionQualityUpdate dco_decode_ui_connection_quality_update(
    dynamic raw,
  );

  @protected
  UIPairReaction dco_decode_ui_pair_reaction(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  UiPromiseResultString
  sse_decode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIPromiseResultString(
    SseDeserializer deserializer,
  );

  @protected
  UiResolverUiPairReaction
  sse_decode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIResolverUIPairReaction(
    SseDeserializer deserializer,
  );

  @protected
  AppState
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    SseDeserializer deserializer,
  );

  @protected
  AppState
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    SseDeserializer deserializer,
  );

  @protected
  AppState
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    SseDeserializer deserializer,
  );

  @protected
  UiPromiseResultString
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIPromiseResultString(
    SseDeserializer deserializer,
  );

  @protected
  UiResolverUiPairReaction
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIResolverUIPairReaction(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<InboundFileEvent> sse_decode_StreamSink_inbound_file_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<InboundPair> sse_decode_StreamSink_inbound_pair_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<OutboundFileStatus>
  sse_decode_StreamSink_outbound_file_status_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<UIConnectionQualityUpdate>
  sse_decode_StreamSink_ui_connection_quality_update_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  InboundPair sse_decode_box_autoadd_inbound_pair(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  InboundFileEvent sse_decode_inbound_file_event(SseDeserializer deserializer);

  @protected
  InboundFileStatus sse_decode_inbound_file_status(
    SseDeserializer deserializer,
  );

  @protected
  InboundPair sse_decode_inbound_pair(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  OutboundFileStatus sse_decode_outbound_file_status(
    SseDeserializer deserializer,
  );

  @protected
  PairingResponse sse_decode_pairing_response(SseDeserializer deserializer);

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  U8Array6 sse_decode_u_8_array_6(SseDeserializer deserializer);

  @protected
  UIConnectionQuality sse_decode_ui_connection_quality(
    SseDeserializer deserializer,
  );

  @protected
  UIConnectionQualityUpdate sse_decode_ui_connection_quality_update(
    SseDeserializer deserializer,
  );

  @protected
  UIPairReaction sse_decode_ui_pair_reaction(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIPromiseResultString(
    UiPromiseResultString self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIResolverUIPairReaction(
    UiResolverUiPairReaction self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    AppState self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    AppState self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    AppState self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIPromiseResultString(
    UiPromiseResultString self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIResolverUIPairReaction(
    UiResolverUiPairReaction self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_inbound_file_event_Sse(
    RustStreamSink<InboundFileEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_inbound_pair_Sse(
    RustStreamSink<InboundPair> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_outbound_file_status_Sse(
    RustStreamSink<OutboundFileStatus> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_ui_connection_quality_update_Sse(
    RustStreamSink<UIConnectionQualityUpdate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_inbound_pair(
    InboundPair self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_inbound_file_event(
    InboundFileEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_inbound_file_status(
    InboundFileStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_inbound_pair(InboundPair self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_outbound_file_status(
    OutboundFileStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pairing_response(
    PairingResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8_array_6(U8Array6 self, SseSerializer serializer);

  @protected
  void sse_encode_ui_connection_quality(
    UIConnectionQuality self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_connection_quality_update(
    UIConnectionQualityUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_pair_reaction(
    UIPairReaction self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIPromiseResultString(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIPromiseResultString(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIPromiseResultString(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIPromiseResultString(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIResolverUIPairReaction(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIResolverUIPairReaction(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIResolverUIPairReaction(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIResolverUIPairReaction(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIPromiseResultString(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIPromiseResultString(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIResolverUIPairReaction(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIResolverUIPairReaction(
    int ptr,
  );
}
