// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/teleport.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiTeleportInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 937523829;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_teleport',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Stream<InboundFile> crateApiTeleportAppStateFileSubscription({
    required AppState that,
  });

  Future<String> crateApiTeleportAppStateGetAddr({required AppState that});

  Future<String?> crateApiTeleportAppStateGetTargetDir({
    required AppState that,
  });

  Future<AppState> crateApiTeleportAppStateInit({
    required String tempDir,
    required String persistenceDir,
  });

  Future<void> crateApiTeleportAppStatePairWith({
    required AppState that,
    required String info,
    required U8Array6 pairingCode,
  });

  Stream<InboundPair> crateApiTeleportAppStatePairingSubscription({
    required AppState that,
  });

  Future<List<(String, String)>> crateApiTeleportAppStatePeers({
    required AppState that,
  });

  Future<void> crateApiTeleportAppStateSendFile({
    required AppState that,
    required String peer,
    required String name,
    required String path,
  });

  Future<void> crateApiTeleportAppStateSetTargetDir({
    required AppState that,
    required String dir,
  });

  Future<void> crateApiTeleportInboundPairReact({
    required InboundPair that,
    required UIPairReaction reaction,
  });

  Future<void> crateApiTeleportInboundPairResult({required InboundPair that});

  Future<void> crateApiTeleportInitApp();

  Future<void> crateApiTeleportInitLogging();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AppState;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AppState;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_AppStatePtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_UiPromiseResultString;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_UiPromiseResultString;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_UiPromiseResultStringPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_UiResolverUiPairReaction;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_UiResolverUiPairReaction;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_UiResolverUiPairReactionPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Stream<InboundFile> crateApiTeleportAppStateFileSubscription({
    required AppState that,
  }) {
    final stream = RustStreamSink<InboundFile>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
              that,
              serializer,
            );
            sse_encode_StreamSink_inbound_file_Sse(stream, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 1,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiTeleportAppStateFileSubscriptionConstMeta,
          argValues: [that, stream],
          apiImpl: this,
        ),
      ),
    );
    return stream.stream;
  }

  TaskConstMeta get kCrateApiTeleportAppStateFileSubscriptionConstMeta =>
      const TaskConstMeta(
        debugName: "AppState_file_subscription",
        argNames: ["that", "stream"],
      );

  @override
  Future<String> crateApiTeleportAppStateGetAddr({required AppState that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTeleportAppStateGetAddrConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTeleportAppStateGetAddrConstMeta =>
      const TaskConstMeta(debugName: "AppState_get_addr", argNames: ["that"]);

  @override
  Future<String?> crateApiTeleportAppStateGetTargetDir({
    required AppState that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTeleportAppStateGetTargetDirConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTeleportAppStateGetTargetDirConstMeta =>
      const TaskConstMeta(
        debugName: "AppState_get_target_dir",
        argNames: ["that"],
      );

  @override
  Future<AppState> crateApiTeleportAppStateInit({
    required String tempDir,
    required String persistenceDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(tempDir, serializer);
          sse_encode_String(persistenceDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTeleportAppStateInitConstMeta,
        argValues: [tempDir, persistenceDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTeleportAppStateInitConstMeta =>
      const TaskConstMeta(
        debugName: "AppState_init",
        argNames: ["tempDir", "persistenceDir"],
      );

  @override
  Future<void> crateApiTeleportAppStatePairWith({
    required AppState that,
    required String info,
    required U8Array6 pairingCode,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
            that,
            serializer,
          );
          sse_encode_String(info, serializer);
          sse_encode_u_8_array_6(pairingCode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTeleportAppStatePairWithConstMeta,
        argValues: [that, info, pairingCode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTeleportAppStatePairWithConstMeta =>
      const TaskConstMeta(
        debugName: "AppState_pair_with",
        argNames: ["that", "info", "pairingCode"],
      );

  @override
  Stream<InboundPair> crateApiTeleportAppStatePairingSubscription({
    required AppState that,
  }) {
    final stream = RustStreamSink<InboundPair>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
              that,
              serializer,
            );
            sse_encode_StreamSink_inbound_pair_Sse(stream, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 6,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiTeleportAppStatePairingSubscriptionConstMeta,
          argValues: [that, stream],
          apiImpl: this,
        ),
      ),
    );
    return stream.stream;
  }

  TaskConstMeta get kCrateApiTeleportAppStatePairingSubscriptionConstMeta =>
      const TaskConstMeta(
        debugName: "AppState_pairing_subscription",
        argNames: ["that", "stream"],
      );

  @override
  Future<List<(String, String)>> crateApiTeleportAppStatePeers({
    required AppState that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_record_string_string,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTeleportAppStatePeersConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTeleportAppStatePeersConstMeta =>
      const TaskConstMeta(debugName: "AppState_peers", argNames: ["that"]);

  @override
  Future<void> crateApiTeleportAppStateSendFile({
    required AppState that,
    required String peer,
    required String name,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
            that,
            serializer,
          );
          sse_encode_String(peer, serializer);
          sse_encode_String(name, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTeleportAppStateSendFileConstMeta,
        argValues: [that, peer, name, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTeleportAppStateSendFileConstMeta =>
      const TaskConstMeta(
        debugName: "AppState_send_file",
        argNames: ["that", "peer", "name", "path"],
      );

  @override
  Future<void> crateApiTeleportAppStateSetTargetDir({
    required AppState that,
    required String dir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
            that,
            serializer,
          );
          sse_encode_String(dir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTeleportAppStateSetTargetDirConstMeta,
        argValues: [that, dir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTeleportAppStateSetTargetDirConstMeta =>
      const TaskConstMeta(
        debugName: "AppState_set_target_dir",
        argNames: ["that", "dir"],
      );

  @override
  Future<void> crateApiTeleportInboundPairReact({
    required InboundPair that,
    required UIPairReaction reaction,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_inbound_pair(that, serializer);
          sse_encode_ui_pair_reaction(reaction, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTeleportInboundPairReactConstMeta,
        argValues: [that, reaction],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTeleportInboundPairReactConstMeta =>
      const TaskConstMeta(
        debugName: "inbound_pair_react",
        argNames: ["that", "reaction"],
      );

  @override
  Future<void> crateApiTeleportInboundPairResult({required InboundPair that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_inbound_pair(that, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTeleportInboundPairResultConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTeleportInboundPairResultConstMeta =>
      const TaskConstMeta(debugName: "inbound_pair_result", argNames: ["that"]);

  @override
  Future<void> crateApiTeleportInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTeleportInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTeleportInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiTeleportInitLogging() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTeleportInitLoggingConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTeleportInitLoggingConstMeta =>
      const TaskConstMeta(debugName: "init_logging", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AppState => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AppState => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_UiPromiseResultString => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIPromiseResultString;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_UiPromiseResultString => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIPromiseResultString;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_UiResolverUiPairReaction => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIResolverUIPairReaction;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_UiResolverUiPairReaction => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIResolverUIPairReaction;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  UiPromiseResultString
  dco_decode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIPromiseResultString(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIPromiseResultString(
      raw,
    );
  }

  @protected
  UiResolverUiPairReaction
  dco_decode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIResolverUIPairReaction(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIResolverUIPairReaction(
      raw,
    );
  }

  @protected
  AppState
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AppStateImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AppState
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AppStateImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AppState
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AppStateImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  UiPromiseResultString
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIPromiseResultString(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return UiPromiseResultStringImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  UiResolverUiPairReaction
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIResolverUIPairReaction(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return UiResolverUiPairReactionImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  RustStreamSink<InboundFile> dco_decode_StreamSink_inbound_file_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<InboundPair> dco_decode_StreamSink_inbound_pair_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  InboundPair dco_decode_box_autoadd_inbound_pair(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_inbound_pair(raw);
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  InboundFile dco_decode_inbound_file(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return InboundFile(
      peer: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      size: dco_decode_u_64(arr[2]),
      path: dco_decode_String(arr[3]),
    );
  }

  @protected
  InboundPair dco_decode_inbound_pair(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return InboundPair(
      peer: dco_decode_String(arr[0]),
      friendlyName: dco_decode_String(arr[1]),
      pairingCode: dco_decode_u_8_array_6(arr[2]),
      reaction:
          dco_decode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIResolverUIPairReaction(
            arr[3],
          ),
      outcome:
          dco_decode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIPromiseResultString(
            arr[4],
          ),
    );
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_string).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_String(arr[1]));
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  U8Array6 dco_decode_u_8_array_6(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return U8Array6(dco_decode_list_prim_u_8_strict(raw));
  }

  @protected
  UIPairReaction dco_decode_ui_pair_reaction(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return UIPairReaction.values[raw as int];
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  UiPromiseResultString
  sse_decode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIPromiseResultString(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner =
        sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIPromiseResultString(
          deserializer,
        );
    return inner;
  }

  @protected
  UiResolverUiPairReaction
  sse_decode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIResolverUIPairReaction(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner =
        sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIResolverUIPairReaction(
          deserializer,
        );
    return inner;
  }

  @protected
  AppState
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AppStateImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AppState
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AppStateImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AppState
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AppStateImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  UiPromiseResultString
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIPromiseResultString(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return UiPromiseResultStringImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  UiResolverUiPairReaction
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIResolverUIPairReaction(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return UiResolverUiPairReactionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<InboundFile> sse_decode_StreamSink_inbound_file_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<InboundPair> sse_decode_StreamSink_inbound_pair_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  InboundPair sse_decode_box_autoadd_inbound_pair(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_inbound_pair(deserializer));
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  InboundFile sse_decode_inbound_file(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_peer = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_size = sse_decode_u_64(deserializer);
    var var_path = sse_decode_String(deserializer);
    return InboundFile(
      peer: var_peer,
      name: var_name,
      size: var_size,
      path: var_path,
    );
  }

  @protected
  InboundPair sse_decode_inbound_pair(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_peer = sse_decode_String(deserializer);
    var var_friendlyName = sse_decode_String(deserializer);
    var var_pairingCode = sse_decode_u_8_array_6(deserializer);
    var var_reaction =
        sse_decode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIResolverUIPairReaction(
          deserializer,
        );
    var var_outcome =
        sse_decode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIPromiseResultString(
          deserializer,
        );
    return InboundPair(
      peer: var_peer,
      friendlyName: var_friendlyName,
      pairingCode: var_pairingCode,
      reaction: var_reaction,
      outcome: var_outcome,
    );
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_string(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  U8Array6 sse_decode_u_8_array_6(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return U8Array6(inner);
  }

  @protected
  UIPairReaction sse_decode_ui_pair_reaction(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return UIPairReaction.values[inner];
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIPromiseResultString(
    UiPromiseResultString self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIPromiseResultString(
      self,
      serializer,
    );
  }

  @protected
  void
  sse_encode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIResolverUIPairReaction(
    UiResolverUiPairReaction self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIResolverUIPairReaction(
      self,
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    AppState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AppStateImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    AppState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AppStateImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAppState(
    AppState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AppStateImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIPromiseResultString(
    UiPromiseResultString self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as UiPromiseResultStringImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIResolverUIPairReaction(
    UiResolverUiPairReaction self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as UiResolverUiPairReactionImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_inbound_file_Sse(
    RustStreamSink<InboundFile> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_inbound_file,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_inbound_pair_Sse(
    RustStreamSink<InboundPair> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_inbound_pair,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_box_autoadd_inbound_pair(
    InboundPair self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_inbound_pair(self, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_inbound_file(InboundFile self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.peer, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_u_64(self.size, serializer);
    sse_encode_String(self.path, serializer);
  }

  @protected
  void sse_encode_inbound_pair(InboundPair self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.peer, serializer);
    sse_encode_String(self.friendlyName, serializer);
    sse_encode_u_8_array_6(self.pairingCode, serializer);
    sse_encode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIResolverUIPairReaction(
      self.reaction,
      serializer,
    );
    sse_encode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUIPromiseResultString(
      self.outcome,
      serializer,
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_string(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_u_8_array_6(U8Array6 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.inner, serializer);
  }

  @protected
  void sse_encode_ui_pair_reaction(
    UIPairReaction self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}

@sealed
class AppStateImpl extends RustOpaque implements AppState {
  // Not to be used by end users
  AppStateImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  AppStateImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_AppState,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_AppState,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_AppStatePtr,
  );

  Stream<InboundFile> fileSubscription() =>
      RustLib.instance.api.crateApiTeleportAppStateFileSubscription(that: this);

  Future<String> getAddr() =>
      RustLib.instance.api.crateApiTeleportAppStateGetAddr(that: this);

  Future<String?> getTargetDir() =>
      RustLib.instance.api.crateApiTeleportAppStateGetTargetDir(that: this);

  Future<void> pairWith({
    required String info,
    required U8Array6 pairingCode,
  }) => RustLib.instance.api.crateApiTeleportAppStatePairWith(
    that: this,
    info: info,
    pairingCode: pairingCode,
  );

  Stream<InboundPair> pairingSubscription() => RustLib.instance.api
      .crateApiTeleportAppStatePairingSubscription(that: this);

  Future<List<(String, String)>> peers() =>
      RustLib.instance.api.crateApiTeleportAppStatePeers(that: this);

  Future<void> sendFile({
    required String peer,
    required String name,
    required String path,
  }) => RustLib.instance.api.crateApiTeleportAppStateSendFile(
    that: this,
    peer: peer,
    name: name,
    path: path,
  );

  Future<void> setTargetDir({required String dir}) => RustLib.instance.api
      .crateApiTeleportAppStateSetTargetDir(that: this, dir: dir);
}

@sealed
class UiPromiseResultStringImpl extends RustOpaque
    implements UiPromiseResultString {
  // Not to be used by end users
  UiPromiseResultStringImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  UiPromiseResultStringImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_increment_strong_count_UiPromiseResultString,
    rustArcDecrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_UiPromiseResultString,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_UiPromiseResultStringPtr,
  );
}

@sealed
class UiResolverUiPairReactionImpl extends RustOpaque
    implements UiResolverUiPairReaction {
  // Not to be used by end users
  UiResolverUiPairReactionImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  UiResolverUiPairReactionImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_increment_strong_count_UiResolverUiPairReaction,
    rustArcDecrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_UiResolverUiPairReaction,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_UiResolverUiPairReactionPtr,
  );
}
