// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> initLogging() =>
    RustLib.instance.api.crateApiTeleportInitLogging();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AppState>>
abstract class AppState implements RustOpaqueInterface {
  Future<String> getAddr();

  static Future<AppState> init({
    required String tempDir,
    required String persistenceDir,
  }) => RustLib.instance.api.crateApiTeleportAppStateInit(
    tempDir: tempDir,
    persistenceDir: persistenceDir,
  );

  Future<void> pairWith({required String info});

  Stream<String> pairingSubscription();

  Future<List<(String, String)>> peers();
}
