// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'teleport.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `new`, `new`, `resolve`, `result`

Future<void> initLogging() =>
    RustLib.instance.api.crateApiTeleportInitLogging();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AppState>>
abstract class AppState implements RustOpaqueInterface {
  Stream<UIConnectionQualityUpdate> connQualitySubscription();

  Stream<InboundFileEvent> fileSubscription();

  Future<String> getAddr();

  Future<String> getDeviceName();

  Future<String?> getTargetDir();

  static Future<AppState> init({required String persistenceDir}) => RustLib
      .instance
      .api
      .crateApiTeleportAppStateInit(persistenceDir: persistenceDir);

  Future<PairingResponse> pairWith({
    required String info,
    required U8Array6 pairingCode,
  });

  Stream<InboundPair> pairingSubscription();

  Future<List<(String, String)>> peers();

  Stream<OutboundFileStatus> sendFile({
    required String peer,
    required String name,
    required SendFileSource source,
  });

  Future<void> setDeviceName({required String name});

  Future<void> setTargetDir({required String dir});
}

class InboundFileEvent {
  final String peer;
  final String peerName;
  final String fileName;
  final InboundFileStatus event;

  const InboundFileEvent({
    required this.peer,
    required this.peerName,
    required this.fileName,
    required this.event,
  });

  @override
  int get hashCode =>
      peer.hashCode ^ peerName.hashCode ^ fileName.hashCode ^ event.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InboundFileEvent &&
          runtimeType == other.runtimeType &&
          peer == other.peer &&
          peerName == other.peerName &&
          fileName == other.fileName &&
          event == other.event;
}

@freezed
sealed class InboundFileStatus with _$InboundFileStatus {
  const InboundFileStatus._();

  const factory InboundFileStatus.progress({
    required BigInt offset,
    required BigInt size,
  }) = InboundFileStatus_Progress;
  const factory InboundFileStatus.done({
    required String path,
    required String name,
  }) = InboundFileStatus_Done;
  const factory InboundFileStatus.error(String field0) =
      InboundFileStatus_Error;
}

class InboundPair {
  final String peer;
  final String friendlyName;
  final U8Array6 pairingCode;
  final UiResolverUiPairReaction reaction;
  final UiPromiseResultString outcome;

  const InboundPair({
    required this.peer,
    required this.friendlyName,
    required this.pairingCode,
    required this.reaction,
    required this.outcome,
  });

  Future<void> react({required UIPairReaction reaction}) => RustLib.instance.api
      .crateApiTeleportInboundPairReact(that: this, reaction: reaction);

  Future<void> result() =>
      RustLib.instance.api.crateApiTeleportInboundPairResult(that: this);

  @override
  int get hashCode =>
      peer.hashCode ^
      friendlyName.hashCode ^
      pairingCode.hashCode ^
      reaction.hashCode ^
      outcome.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InboundPair &&
          runtimeType == other.runtimeType &&
          peer == other.peer &&
          friendlyName == other.friendlyName &&
          pairingCode == other.pairingCode &&
          reaction == other.reaction &&
          outcome == other.outcome;
}

@freezed
sealed class OutboundFileStatus with _$OutboundFileStatus {
  const OutboundFileStatus._();

  const factory OutboundFileStatus.progress({
    required BigInt offset,
    required BigInt size,
  }) = OutboundFileStatus_Progress;
  const factory OutboundFileStatus.done() = OutboundFileStatus_Done;
  const factory OutboundFileStatus.error(String field0) =
      OutboundFileStatus_Error;
}

@freezed
sealed class PairingResponse with _$PairingResponse {
  const PairingResponse._();

  const factory PairingResponse.success() = PairingResponse_Success;
  const factory PairingResponse.wrongCode() = PairingResponse_WrongCode;
  const factory PairingResponse.wrongSecret() = PairingResponse_WrongSecret;
  const factory PairingResponse.error(String field0) = PairingResponse_Error;
}

@freezed
sealed class SendFileSource with _$SendFileSource {
  const SendFileSource._();

  const factory SendFileSource.path(String field0) = SendFileSource_Path;
  const factory SendFileSource.fd(int field0) = SendFileSource_Fd;
}

enum UIConnectionQuality { direct, mixed, relay, none }

class UIConnectionQualityUpdate {
  final String peer;
  final UIConnectionQuality quality;

  const UIConnectionQualityUpdate({required this.peer, required this.quality});

  @override
  int get hashCode => peer.hashCode ^ quality.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UIConnectionQualityUpdate &&
          runtimeType == other.runtimeType &&
          peer == other.peer &&
          quality == other.quality;
}

enum UIPairReaction { accept, reject, wrongPairingCode }
