// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> initLogging() =>
    RustLib.instance.api.crateApiTeleportInitLogging();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AppState>>
abstract class AppState implements RustOpaqueInterface {
  Stream<InboundFile> fileSubscription();

  Future<String> getAddr();

  Future<String?> getTargetDir();

  static Future<AppState> init({
    required String tempDir,
    required String persistenceDir,
  }) => RustLib.instance.api.crateApiTeleportAppStateInit(
    tempDir: tempDir,
    persistenceDir: persistenceDir,
  );

  Future<void> pairWith({required String info});

  Stream<String> pairingSubscription();

  Future<List<(String, String)>> peers();

  Future<void> sendFile({
    required String peer,
    required String name,
    required String path,
  });

  Future<void> setTargetDir({required String dir});
}

class InboundFile {
  final String peer;
  final String name;
  final BigInt size;
  final String path;

  const InboundFile({
    required this.peer,
    required this.name,
    required this.size,
    required this.path,
  });

  @override
  int get hashCode =>
      peer.hashCode ^ name.hashCode ^ size.hashCode ^ path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InboundFile &&
          runtimeType == other.runtimeType &&
          peer == other.peer &&
          name == other.name &&
          size == other.size &&
          path == other.path;
}
